DATA:
  DATA_LOADER: TorchDataLoader
  DATA_ROOT: ""
  TRAIN_DATA:
    - TYPE: TorchCIFAR10
      IS_TRAIN: True
      DO_SHUFFLE: True
      DATA_PATH: ./data
      TRANSFORM:
        - TYPE: ToTensor
        - TYPE: Normalize
          MEAN: [0.5, 0.5, 0.5]
          STD: [0.5, 0.5, 0.5]
  TEST_DATA:
    - TYPE: TorchCIFAR10
      DATA_PATH: ./data
      TRANSFORM:
        - TYPE: ToTensor
        - TYPE: Normalize
          MEAN: [0.5, 0.5, 0.5]
          STD: [0.5, 0.5, 0.5]
