BASE:
  - models/backbone/basic_vgg.yaml
  - models/head/basic_linear.yaml
  - solvers/basic_classifier.yaml
  - dataset/basic_classifier.yaml

SOLVER:
  BASE_LR: 0.003
  MAX_EPOCH: 100

DATA:
  TOTAL_BATCH: 128
  NUM_GPU: 1

EVALUATION:
  TYPE: BasicACC

PRIMARY_CONFIG: basic_classifier.yaml
