BASE:
  - models/backbone/basic_vgg.yaml
  - models/head/basic_linear.yaml
  - solvers/basic_classifier.yaml
  - dataset/basic_classifier.yaml

SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 10

TOTAL_BATCH: 64

EVALUATION:
  TYPE: BasicACC

BASE_CONFIG: basic_classifier.yaml
